In [1]:
import pandas as pd
import numpy as np

Synetuc user data set

In [ ]:
data = {
    "age": [45, 28, 60, 35],
    "gender": ["M", "F", "M", "F"],
    "height": [1.65, 1.58, 1.70, 1.62],   # meters
    "weight": [82, 55, 90, 68],          # kg
    "activity_level": ["low", "moderate", "low", "moderate"],
    "daily_calories": [2800, 1800, 3000, 2200],
    "sugar": [65, 30, 70, 40],           # grams
    "sodium": [2600, 1200, 2800, 1800]   # mg
}

df = pd.DataFrame(data)
df

   age gender  height  weight activity_level  daily_calories  sugar  sodium
0   45      M    1.65      82            low            2800     65    2600
1   28      F    1.58      55       moderate            1800     30    1200
2   60      M    1.70      90            low            3000     70    2800
3   35      F    1.62      68       moderate            2200     40    1800

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4 non-null      int64
 1   gender          4 non-null      object
 2   height          4 non-null      float64
 3   weight          4 non-null      int64
 4   activity_level  4 non-null      object
 5   daily_calories  4 non-null      int64
 6   sugar           4 non-null      int64
 7   sodium          4 non-null      int64
dtypes: float64(1), int64(5), object(2)
memory usage: 388.0+ bytes

In [ ]:
df.isnull().sum()

age               0
gender            0
height            0
weight            0
activity_level    0
daily_calories    0
sugar             0
sodium            0
dtype: int64

BMI Calculation

In [ ]:
df["BMI"] = df["weight"] / (df["height"] ** 2)
df["BMI"] = df["BMI"].round(2)

df[["weight", "height", "BMI"]]

   weight  height    BMI
0      82    1.65  30.12
1      55    1.58  22.03
2      90    1.70  31.14
3      68    1.62  25.91

Categorize BMI

In [ ]:
def bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif bmi < 25:
        return "Normal"
    elif bmi < 30:
        return "Overweight"
    else:
        return "Obese"

df["BMI_Category"] = df["BMI"].apply(bmi_category)
df[["BMI", "BMI_Category"]]

     BMI BMI_Category
0  30.12        Obese
1  22.03       Normal
2  31.14        Obese
3  25.91   Overweight

Health Risk Preidction

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

load  the data set

In [ ]:
import pandas as pd

df = pd.read_excel("/content/synthetic_health_risk_dataset_500.xlsx")
df.head()

,age,gender,daily_calories,sugar_g,sodium_mg,carbohydrate_g,fat_g,diabetes_risk,hypertension_risk,obesity_risk
0,56,F,3086,56,1888,154,98,High,Moderate,High
1,69,M,1580,75,920,176,32,High,Low,Low
2,46,M,1632,47,3250,309,116,Moderate,High,High
3,32,F,2296,60,1768,298,119,High,Moderate,High
4,60,M,2399,72,983,413,66,High,Low,Moderate

In [ ]:
label_encoders = {}

categorical_columns = ["gender", "diabetes_risk", "hypertension_risk", "obesity_risk"]

for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

Select inputs

In [ ]:
X = df[
    ["age", "gender", "daily_calories", "sugar_g",
     "sodium_mg", "carbohydrate_g", "fat_g"]
]

Disease wise Model training

Type -2 Dibates

In [ ]:
y_diabetes = df["diabetes_risk"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y_diabetes, test_size=0.2, random_state=42
)

diabetes_model = RandomForestClassifier(n_estimators=100, random_state=42)
diabetes_model.fit(X_train, y_train)

y_pred = diabetes_model.predict(X_test)

print("Diabetes Risk Prediction Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Diabetes Risk Prediction Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        55
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        28

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

Hypertension Risk

In [ ]:
y_hypertension = df["hypertension_risk"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y_hypertension, test_size=0.2, random_state=42
)

hypertension_model = RandomForestClassifier(n_estimators=100, random_state=42)
hypertension_model.fit(X_train, y_train)

y_pred = hypertension_model.predict(X_test)

print("Hypertension Risk Prediction Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Hypertension Risk Prediction Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        48
           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        33

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

Obesity

In [ ]:
y_obesity = df["obesity_risk"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y_obesity, test_size=0.2, random_state=42
)

obesity_model = RandomForestClassifier(n_estimators=100, random_state=42)
obesity_model.fit(X_train, y_train)

y_pred = obesity_model.predict(X_test)

print("Obesity Risk Prediction Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Obesity Risk Prediction Accuracy: 0.96
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        56
           1       1.00      0.75      0.86        16
           2       0.88      1.00      0.93        28

    accuracy                           0.96       100
   macro avg       0.96      0.92      0.93       100
weighted avg       0.96      0.96      0.96       100

Predict Risk For New user(Demo)

In [ ]:
import pandas as pd

# 1. Define 10 users to show the model's versatility
test_users_data = [
    {"user_id": 1001, "age": 45, "gender": "M", "daily_calories": 2800, "sugar_g": 65,  "sodium_mg": 2600, "carbohydrate_g": 350, "fat_g": 95},
    {"user_id": 1002, "age": 30, "gender": "F", "daily_calories": 1800, "sugar_g": 25,  "sodium_mg": 1400, "carbohydrate_g": 200, "fat_g": 55},
    {"user_id": 1003, "age": 60, "gender": "M", "daily_calories": 3200, "sugar_g": 110, "sodium_mg": 3800, "carbohydrate_g": 450, "fat_g": 105},
    {"user_id": 1004, "age": 52, "gender": "F", "daily_calories": 2400, "sugar_g": 70,  "sodium_mg": 2900, "carbohydrate_g": 320, "fat_g": 85},
    {"user_id": 1005, "age": 27, "gender": "M", "daily_calories": 2000, "sugar_g": 30,  "sodium_mg": 1500, "carbohydrate_g": 230, "fat_g": 60},
    {"user_id": 1006, "age": 65, "gender": "F", "daily_calories": 2600, "sugar_g": 95,  "sodium_mg": 3400, "carbohydrate_g": 380, "fat_g": 100},
    {"user_id": 1007, "age": 40, "gender": "M", "daily_calories": 2200, "sugar_g": 45,  "sodium_mg": 2100, "carbohydrate_g": 280, "fat_g": 75},
    {"user_id": 1008, "age": 35, "gender": "F", "daily_calories": 1900, "sugar_g": 35,  "sodium_mg": 1700, "carbohydrate_g": 240, "fat_g": 65},
    {"user_id": 1009, "age": 58, "gender": "M", "daily_calories": 3000, "sugar_g": 90,  "sodium_mg": 3600, "carbohydrate_g": 410, "fat_g": 98},
    {"user_id": 1010, "age": 48, "gender": "F", "daily_calories": 2300, "sugar_g": 55,  "sodium_mg": 2500, "carbohydrate_g": 300, "fat_g": 80}
]

print("--- PROCESS 04: MULTI-USER RISK PREDICTION --- \n")

for user in test_users_data:
    # Prepare the data for the model
    user_df = pd.DataFrame([{
        "age": user["age"],
        "gender": label_encoders["gender"].transform([user["gender"]])[0],
        "daily_calories": user["daily_calories"],
        "sugar_g": user["sugar_g"],
        "sodium_mg": user["sodium_mg"],
        "carbohydrate_g": user["carbohydrate_g"],
        "fat_g": user["fat_g"]
    }])

    # Predict using your models
    diabetes_risk = diabetes_model.predict(user_df)
    hypertension_risk = hypertension_model.predict(user_df)
    obesity_risk = obesity_model.predict(user_df)

    # Convert numeric predictions back to labels
    d_label = label_encoders["diabetes_risk"].inverse_transform(diabetes_risk)[0]
    h_label = label_encoders["hypertension_risk"].inverse_transform(hypertension_risk)[0]
    o_label = label_encoders["obesity_risk"].inverse_transform(obesity_risk)[0]

    # Print the output
    print(f"User ID: {user['user_id']}")
    print(f"  - Predicted Diabetes Risk: {d_label}")
    print(f"  - Predicted Hypertension Risk: {h_label}")
    print(f"  - Predicted Obesity Risk: {o_label}")
    print("-" * 40)

--- PROCESS 04: MULTI-USER RISK PREDICTION ---

User ID: 1001
  - Predicted Diabetes Risk: High
  - Predicted Hypertension Risk: High
  - Predicted Obesity Risk: High
----------------------------------------
User ID: 1002
  - Predicted Diabetes Risk: Low
  - Predicted Hypertension Risk: Low
  - Predicted Obesity Risk: Low
----------------------------------------
User ID: 1003
  - Predicted Diabetes Risk: High
  - Predicted Hypertension Risk: High
  - Predicted Obesity Risk: High
----------------------------------------
User ID: 1004
  - Predicted Diabetes Risk: High
  - Predicted Hypertension Risk: High
  - Predicted Obesity Risk: Moderate
----------------------------------------
User ID: 1005
  - Predicted Diabetes Risk: Moderate
  - Predicted Hypertension Risk: Moderate
  - Predicted Obesity Risk: Moderate
----------------------------------------
User ID: 1006
  - Predicted Diabetes Risk: High
  - Predicted Hypertension Risk: High
  - Predicted Obesity Risk: High
----------------------------------------
User ID: 1007
  - Predicted Diabetes Risk: Moderate
  - Predicted Hypertension Risk: Moderate
  - Predicted Obesity Risk: Moderate
----------------------------------------
User ID: 1008
  - Predicted Diabetes Risk: Moderate
  - Predicted Hypertension Risk: Moderate
  - Predicted Obesity Risk: Moderate
----------------------------------------
User ID: 1009
  - Predicted Diabetes Risk: High
  - Predicted Hypertension Risk: High
  - Predicted Obesity Risk: High
----------------------------------------
User ID: 1010
  - Predicted Diabetes Risk: High
  - Predicted Hypertension Risk: High
  - Predicted Obesity Risk: Moderate
----------------------------------------

Personalized reccomendations demo

In [ ]:
import pandas as pd

# 1. Setup Sample Users (Simulating the database)
test_users = [
    {"id": "U101", "name": "Aruni", "age": 45, "gender": "F", "cal": 2800, "sugar": 75, "sodium": 2600, "carb": 350},
    {"id": "U102", "name": "Kasun", "age": 28, "gender": "M", "cal": 2100, "sugar": 20, "sodium": 1400, "carb": 220},
    {"id": "U103", "name": "Perera", "age": 60, "gender": "M", "cal": 3100, "sugar": 90, "sodium": 3500, "carb": 400}
]

def generate_report(user):
    # Prepare data for prediction
    # (Assuming your models are already loaded as 'diabetes_model', etc.)
    input_data = pd.DataFrame([{
        "age": user["age"],
        "gender": label_encoders["gender"].transform([user["gender"]])[0],
        "daily_calories": user["cal"],
        "sugar_g": user["sugar"],
        "sodium_mg": user["sodium"],
        "carbohydrate_g": user["carb"],
        "fat_g": 80 # Placeholder for fat
    }])

    # Get Predictions
    d_risk = label_encoders["diabetes_risk"].inverse_transform(diabetes_model.predict(input_data))[0]
    h_risk = label_encoders["hypertension_risk"].inverse_transform(hypertension_model.predict(input_data))[0]
    o_risk = label_encoders["obesity_risk"].inverse_transform(obesity_model.predict(input_data))[0]

    # --- RECOMMENDATION ENGINE LOGIC ---
    recommendations = []

    # Sugar/Diabetes Logic
    if d_risk == "High" or user["sugar"] > 50:
        recommendations.append(" SUGAR ALERT: Your intake is significantly high. Replace refined white sugar with Kitul Jaggery or Stevia.")
        recommendations.append(" STAPLE SWAP: Transition from White Rice to Red Basmati or Kurakkan-based meals to manage glycemic spikes.")

    # Sodium/Hypertension Logic
    if h_risk == "High" or user["sodium"] > 2300:
        recommendations.append(" SODIUM REDUCTION: Limit 'Bites', processed sausages, and excessive salt in your Pol Sambol.")
        recommendations.append(" HERBAL BOOST: Use more lime, ginger, and garlic in curries to enhance flavor without adding salt.")

    # Obesity/Calorie Logic
    if o_risk == "High" or user["cal"] > 2500:
        recommendations.append(" PORTION CONTROL: Follow the 'Healthy Plate' rule—fill 50% of your plate with local Mellun and vegetables.")

    # If everything is fine
    if not recommendations:
        recommendations.append(" Excellent balance! Continue your current dietary habits and stay hydrated.")

    return d_risk, h_risk, o_risk, recommendations

# 2. Loop through all customers and print reports
print("="*60)
print("      NUTRI SCANNER: PERSONALIZED HEALTH DASHBOARD      ")
print("="*60)

for user in test_users:
    d, h, o, advice = generate_report(user)

    print(f"\n[USER ID: {user['id']} | NAME: {user['name']}]")
    print(f"Stats: {user['cal']} kcal, {user['sugar']}g Sugar, {user['sodium']}mg Sodium")
    print(f"Predicted Risks: Diabetes: {d} | Hypertension: {h} | Obesity: {o}")
    print("-" * 30)
    print("PERSONALIZED ADVICE:")
    for item in advice:
        print(f"  * {item}")
    print("\n" + "."*60)

============================================================
      NUTRI SCANNER: PERSONALIZED HEALTH DASHBOARD
============================================================

[USER ID: U101 | NAME: Aruni]
Stats: 2800 kcal, 75g Sugar, 2600mg Sodium
Predicted Risks: Diabetes: High | Hypertension: High | Obesity: High
------------------------------
PERSONALIZED ADVICE:
  *  SUGAR ALERT: Your intake is significantly high. Replace refined white sugar with Kitul Jaggery or Stevia.
  *  STAPLE SWAP: Transition from White Rice to Red Basmati or Kurakkan-based meals to manage glycemic spikes.
  *  SODIUM REDUCTION: Limit 'Bites', processed sausages, and excessive salt in your Pol Sambol.
  *  HERBAL BOOST: Use more lime, ginger, and garlic in curries to enhance flavor without adding salt.
  *  PORTION CONTROL: Follow the 'Healthy Plate' rule—fill 50% of your plate with local Mellun and vegetables.

............................................................

[USER ID: U102 | NAME: Kasun]
Stats: 2100 kcal, 20g Sugar, 1400mg Sodium
Predicted Risks: Diabetes: Low | Hypertension: Low | Obesity: Moderate
------------------------------
PERSONALIZED ADVICE:
  *  Excellent balance! Continue your current dietary habits and stay hydrated.

............................................................

[USER ID: U103 | NAME: Perera]
Stats: 3100 kcal, 90g Sugar, 3500mg Sodium
Predicted Risks: Diabetes: High | Hypertension: High | Obesity: High
------------------------------
PERSONALIZED ADVICE:
  *  SUGAR ALERT: Your intake is significantly high. Replace refined white sugar with Kitul Jaggery or Stevia.
  *  STAPLE SWAP: Transition from White Rice to Red Basmati or Kurakkan-based meals to manage glycemic spikes.
  *  SODIUM REDUCTION: Limit 'Bites', processed sausages, and excessive salt in your Pol Sambol.
  *  HERBAL BOOST: Use more lime, ginger, and garlic in curries to enhance flavor without adding salt.
  *  PORTION CONTROL: Follow the 'Healthy Plate' rule—fill 50% of your plate with local Mellun and vegetables.

............................................................

Health Risk Visualization